### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by umbundu** [ludvigbruchmann/motus#1]
This is a beautiful framework! Congratulations. Do you have any plans to add navigation and tabs?
Thanks,
Everardo

**Comment by alexampersandria** [comment]
Motus is meant to a foundation to build a website upon, unlike other frameworks such as bootstrap. So making a standard navigation bar isn't a high priority, but I might add it at some point. And adding tabs actually sound like a really good idea.

**Comment by umbundu** [comment]
Thank you so much!

**Comment by alexampersandria** [comment]
Navigational elements have been in added in [2.1.0 Aluminium](https://github.com/ludvigbruchmann/motus/releases/tag/2.1.0)

This is a few years late, but better late than never I suppose :smile:
